# 日志配置
logging:
    config: classpath:log4j2-spring.xml
    level:
        com.xms: info
        org.springframework: warn
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为8080
  port: 18866
  servlet:
    # 应用的访问路径
    context-path: /
  undertow:
    threads:
      # 设置IO线程数, 它主要执行非阻塞的任务,它们会负责多个连接, 默认设置每个CPU核心一个线程
      io: 16
      # 阻塞任务线程池, 当执行类似servlet请求阻塞操作, undertow会从这个线程池中取得线程,它的值设置取决于系统的负载
      worker: 999
      # 以下的配置会影响buffer,这些buffer会用于服务器连接的IO操作,有点类似netty的池化内存管理
    buffer-size: 1024
    # 是否分配的直接内存
    direct-buffers: true

# 数据源配置
spring:
    # 服务模块
    devtools:
        restart:
            # 热部署开关
            enabled: false
    # redis 配置 boot3微调
    data:
      redis:
          # 地址
          host: localhost
          # 端口，默认为6379
          port: 6379
          # 密码
          password: VVuz892aa
          # 连接超时时间
          timeout: 10000
          database: 0
          lettuce:
              pool:
                  # 连接池中的最小空闲连接
                  min-idle: 0
                  # 连接池中的最大空闲连接
                  max-idle: 8
                  # 连接池的最大数据库连接数
                  max-active: 8
                  # #连接池最大阻塞等待时间（使用负值表示没有限制）
                  max-wait: -1
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.cj.jdbc.Driver
        druid:
            # 主库数据源
            master:
                url: jdbc:mysql://localhost:3306/xmsdfc?useUnicode=true&allowMultiQueries=true&rewriteBatchedStatements=true&useAffectedRows=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&autoReconnect=true&autoReconnectForPools=true&connectTimeout=30000&socketTimeout=60000&useSSL=false&serverTimezone=GMT%2B8
                username: root
                password: LBA4uxF2
            # 从库数据源
            slave:
                # 从数据源开关/默认关闭
                enabled: false
                url:
                username:
                password:
            # 初始连接数
            initialSize: 5
            # 最小连接池数量
            minIdle: 10
            # 最大连接池数量
            maxActive: 20
            # 配置获取连接等待超时的时间
            maxWait: 60000
            # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
            timeBetweenEvictionRunsMillis: 50000
            # 配置一个连接在池中最小生存的时间，单位是毫秒
            minEvictableIdleTimeMillis: 300000
            # 配置一个连接在池中最大生存的时间，单位是毫秒
            maxEvictableIdleTimeMillis: 900000
            # 配置检测连接是否有效
            validationQuery: SELECT 1 FROM DUAL
            testWhileIdle: true
            testOnBorrow: false
            testOnReturn: false
            webStatFilter:
                enabled: true
            statViewServlet:
                enabled: true
                # 设置白名单，不填则允许所有访问
                allow:
                url-pattern: /druid/*
                login-username: admin
                login-password: aleo-@42ed43X09d3898784a.
            filter:
                stat:
                    enabled: true
                    # 慢SQL记录
                    log-slow-sql: true
                    slow-sql-millis: 1000
                    merge-sql: true
                wall:
                    config:
                        multi-statement-allow: true

OSS: # 默认为七牛云OSS存储
  # 公钥
   accessKey: D8n5VUrnrHHAFtmby6QAvxT6D34utrTNrPK4Na2n
  # 私钥
   secretKey: kBvlxYohjMh-HUY2YeCQxNDAfqz199vVWJ0jgFKS
  # 存储空间名
   bucketName: starpics
  # 域名/路径
   path: https://www.gylk.xyz
  #是否开启
   enabled: false
   channel: local
file:
    # 上传文件允许的扩展名
    allowed: png,jpg,jpeg,pdf,bmp
#项目模块集中配置
renegade:
    #分布式锁配置
    redisson:
        ##是否启用分布式锁
        enabled: true
        ##将docker脚本部署的redis服务映射为宿主机ip
        address: redis://localhost:6379
        password: VVuz892aa
        database: 0
#canal中间件配置, binlog只允许row，不允许其他，否则无法解析
canal:
  #实例，要跟服务端的一一对应
  destination: xmsdfc
  #服务地址
  server: 127.0.0.1:11111
  # 模式  内嵌：simpleDiy  关闭：simpleDiyOff 其他的自己代码层看
  mode: simpleDiy
  # 订阅监听的库表。一定要设置
  # table regex 	mysql 数据解析关注的表，Perl正则表达式.多个正则之间以逗号(,)分隔，转义符需要双斜杠(\)
  #常见例子：1. 所有表：.* or .\… 2. canal schema下所有表： canal\…* 3. canal下的以canal打头的表：canal\.canal.*
  #4. canal schema下的一张表：canal.test1 5. 多个规则组合使用：canal\…*,mysql.test1,mysql.test2 (逗号分隔)
  # .*\\..* 所有的
  filter: xmsdfc.t_user_money
  #是否异步处理
  async: false

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: tldzqjysvduqsdybnnldbkksfgpbglcqfhujbqbxbcbgdtabfophxxtdpzmuanqjlqwkqihpujdlsfqbztxwmzrdpglmreshlfkyljizkrvbthwewgpqoendfloxxhclyzdilcepdafzofizibjyslguddpynoahwkszqkggxqyxpggsdcmtufnvbipmrzoakcnyygzdqnpdlzjhgbhihnlbwlbvzjlmfazvnfpdmdesnxqthgedqrcrbdonqxukbyytioprcafttuvpwrpucfmxulvalvkcwfnjmavqgrvzaxqeuthltoxkwiziwadjpihyzwpyotttiyrmmbochmtvjdahnwtovmnqzvsvvtroyjqyefqrqgohrlfrmdivpfgktgzxqvoucejsxbretmqbjspdkgxaviqgkkdhecdvltuxanijbneqmglnlrlhwoyifswczglftjcbaydpfcklqpgtbavhvatwrfrcnftpeqcnokoitvgmrogkxnvo
  # 令牌有效期（默认30分钟）
  expireTime: 1440

# 合约配置
contract:
  #TODO 需要改为线上环境的
  #代币 u的合约地址，需要校验
  USDTBS0: '0x55d398326f99059fF775485246999027B3197955'
  #查询充值
  QUERYURL: http://52.77.164.64:9331/chain/order/
  # 提币申请
  WITHDRAWURL: http://52.77.164.64:9331/chain/withdraw
  PRICEURL: http://52.77.164.64:9331/chain/price/
  # 签名 。false代表无需签名
  SIGN: false

#modou yun 短信配置
sms:
  url: https://live2.moduyun.com/sms/v2
  #ak
  accesskey: 67d914962e18300fdc6525f4
  #sk
  accessSecret: f32add463b454063bab343f21edb400c
  #签名
  sign: 67d91e8a2e18300fdc6525fa
  #模版id
  templateId: 67d91b752e18300fdc6525f8
  #短信是否启动
  enabled: true

udun.config:
  domain: https://sig11.udun.io
  merchant: 321160
  key: 94286da2d51a6548746d7015f4964772
  callUrl: https://www.sigmapro.cc/dev-web/udun/callback
  #BEP20代幣
  mainBepCoinType: 2510
  USDTBEP20: '0x55d398326f99059ff775485246999027b3197955'
  #TRX代幣-TRC20
  mainTrcCoinType: 195
  USDTRC20: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t'
  bscApiKey: 'bwopwobO4Zft1tcO9vFuLKMUbqUFWxNo3BRKMypxwgGTcIQ3pJUKmUWfME1FJwqF'
  bscSecretKey: 'dKmF08QQNDrv9hF3lRuUd4czjkfTSNSbt0LuF0ZvDfdTpInSS1wnVtHGIUHlhbKb'

# 对接合约回调md5Key
lq:
  md5Key: "883c6bc288071f537d42315f856c13e4eddb2383db32904"
  baseUrl: "http://172.31.43.207:37771"

df:
  #获取oort价格url
  callDfcUrl: "https://api-spot.weex.com/api/v2/market/ticker?symbol=DFCUSDT_SPBL"

juExchange:
  appId: xd0xee8d78245cdn
  appSecret: d161ev4r35gghrs3h421ifk2acpwtwkbg2w3cslr332l65s31c8ykf2olbitbw0w
  #prod  https://www.jucoin.vc
  #  url: https://www.jcwork.net
  url: https://www.bitport.one
